import type { Item, Chat, Message } from "./types"

export const mockItems: Item[] = [
  {
    id: "item1",
    type: "lost",
    title: "Blue Backpack",
    description: "Lost my blue North Face backpack in the Science Building. It has my laptop and textbooks inside.",
    category: "accessories",
    location: "Science Building",
    date: "2023-05-15",
    imageUrl: "/placeholder.svg?height=300&width=400",
    userId: "user1",
    status: "open",
    createdAt: "2023-05-15T14:30:00Z",
  },
  {
    id: "item2",
    type: "found",
    title: "iPhone 13",
    description: "Found an iPhone 13 in the library. Black case with a sticker on the back.",
    category: "electronics",
    location: "Main Library",
    date: "2023-05-16",
    imageUrl: "/placeholder.svg?height=300&width=400",
    userId: "user2",
    status: "open",
    createdAt: "2023-05-16T10:15:00Z",
  },
  {
    id: "item3",
    type: "lost",
    title: "Textbook - Introduction to Psychology",
    description: "Lost my psychology textbook in the cafeteria. It has my name written on the first page.",
    category: "books",
    location: "Student Center Cafeteria",
    date: "2023-05-14",
    userId: "user1",
    status: "open",
    createdAt: "2023-05-14T16:45:00Z",
  },
  {
    id: "item4",
    type: "found",
    title: "Water Bottle",
    description: "Found a blue Hydro Flask water bottle near the gym entrance.",
    category: "other",
    location: "Gym",
    date: "2023-05-17",
    imageUrl: "/placeholder.svg?height=300&width=400",
    userId: "user3",
    status: "open",
    createdAt: "2023-05-17T08:20:00Z",
  },
  {
    id: "item5",
    type: "lost",
    title: "Glasses",
    description: "Lost my prescription glasses with black frames. I think I left them in Room 302.",
    category: "accessories",
    location: "Room 302, Engineering Building",
    date: "2023-05-13",
    userId: "user2",
    status: "open",
    createdAt: "2023-05-13T13:10:00Z",
  },
  {
    id: "item6",
    type: "found",
    title: "Student ID Card",
    description: "Found a student ID card for Sarah Johnson near the parking lot.",
    category: "other",
    location: "Parking Lot B",
    date: "2023-05-18",
    imageUrl: "/placeholder.svg?height=300&width=400",
    userId: "user3",
    status: "open",
    createdAt: "2023-05-18T15:30:00Z",
  },
]

export const mockChats: Chat[] = [
  {
    id: "chat1",
    name: "Jane Smith",
    lastMessage: "I found your backpack!",
    lastMessageTime: "2023-05-16T14:30:00Z",
    participants: ["current-user", "user2"],
  },
  {
    id: "chat2",
    name: "Mike Johnson",
    lastMessage: "Is the water bottle still available?",
    lastMessageTime: "2023-05-17T10:15:00Z",
    participants: ["current-user", "user3"],
  },
]

export const mockMessages: Message[] = [
  {
    id: "msg1",
    chatId: "chat1",
    senderId: "user2",
    text: "Hi there! I think I found your blue backpack in the Science Building.",
    timestamp: "2023-05-16T14:25:00Z",
  },
  {
    id: "msg2",
    chatId: "chat1",
    senderId: "current-user",
    text: "Oh really? That's great news! Does it have a laptop inside?",
    timestamp: "2023-05-16T14:27:00Z",
  },
  {
    id: "msg3",
    chatId: "chat1",
    senderId: "user2",
    text: "Yes, it has a laptop and some textbooks. Can you describe any other identifying features?",
    timestamp: "2023-05-16T14:28:00Z",
  },
  {
    id: "msg4",
    chatId: "chat1",
    senderId: "current-user",
    text: "It has a small keychain with a blue robot attached to the front pocket.",
    timestamp: "2023-05-16T14:29:00Z",
  },
  {
    id: "msg5",
    chatId: "chat1",
    senderId: "user2",
    text: "I found your backpack!",
    timestamp: "2023-05-16T14:30:00Z",
  },
  {
    id: "msg6",
    chatId: "chat2",
    senderId: "current-user",
    text: "Hello, I saw that you found a water bottle near the gym. Is it still available?",
    timestamp: "2023-05-17T10:10:00Z",
  },
  {
    id: "msg7",
    chatId: "chat2",
    senderId: "user3",
    text: "Yes, I still have it. It's a blue Hydro Flask, right?",
    timestamp: "2023-05-17T10:12:00Z",
  },
  {
    id: "msg8",
    chatId: "chat2",
    senderId: "current-user",
    text: "That sounds like mine! When and where can I pick it up?",
    timestamp: "2023-05-17T10:14:00Z",
  },
  {
    id: "msg9",
    chatId: "chat2",
    senderId: "user3",
    text: "Is the water bottle still available?",
    timestamp: "2023-05-17T10:15:00Z",
  },
]
